version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: secure
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    build: ./api
    image: api-backend
    container_name: go-api
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: secure
      DB_NAME: mydb
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - api


volumes:
  db-data:
